title: Trace Homepage
description: "Homepage of the Trace bot for Discord."
keyword: "Trace, Discord, Bot, Homepage"
homepage: "https://rumbersbot.github.io"
github_repo: "https://github.com/RumblersBot/RumblersBot.github.io"

markdown: kramdown
highlighter: rouge
permalink: pretty

navigation:
- text: Home
  internal: false
  url: ./

theme: jekyll-theme-modernist
show_downloads: false